name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Display help
      run: make help

    - name: Install dependencies
      run: sudo apt-get install make python3 python3-virtualenv

    - name: Install python module
      run: make install

    - name: Run tests
      run: make test
